// <auto-generated />
using System;
using MealTrace.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealTrace.Api.Data.Migrations
{
    [DbContext(typeof(MealTraceDbContext))]
    [Migration("20260930161118_MealExceptionAudit")]
    partial class MealExceptionAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealTrace.Api.Data.AccountPasswordResetAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("UserId", "PerformedAt");

                    b.ToTable("AccountPasswordResetAudits");
                });

            modelBuilder.Entity("MealTrace.Api.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MealTrace.Api.Data.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("EndReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("EndRecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EndedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EndedByUserId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("\"EndDate\" IS NULL");

                    b.HasIndex("StudentId", "StartDate")
                        .IsUnique();

                    b.HasIndex("ClassId", "StartDate", "EndDate");

                    b.ToTable("Enrollments", t =>
                        {
                            t.HasCheckConstraint("CK_Enrollment_Dates", "\"EndDate\" IS NULL OR \"EndDate\" > \"StartDate\"");
                        });
                });

            modelBuilder.Entity("MealTrace.Api.Data.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MealTrace.Api.Data.IngredientVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("EdibleFraction")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EnergyKcalPer100G")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePerKg")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("ProteinGPer100G")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId", "Version")
                        .IsUnique();

                    b.ToTable("IngredientVersions");
                });

            modelBuilder.Entity("MealTrace.Api.Data.InspectorGrant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedById")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("GrantedById");

                    b.ToTable("InspectorGrants");
                });

            modelBuilder.Entity("MealTrace.Api.Data.MealAbsence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("StudentId", "FromDate", "ToDate");

                    b.ToTable("MealAbsences");
                });

            modelBuilder.Entity("MealTrace.Api.Data.MealDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CutoffAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DecisionRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date", "MealType")
                        .IsUnique();

                    b.ToTable("MealDays");
                });

            modelBuilder.Entity("MealTrace.Api.Data.MealEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AmendsId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MealDayId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MealDayId");

                    b.ToTable("MealEvidence");
                });

            modelBuilder.Entity("MealTrace.Api.Data.MealRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealDayId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordedByName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("WillEat")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("StudentId");

                    b.HasIndex("MealDayId", "StudentId", "RecordedAt");

                    b.HasIndex("MealDayId", "StudentId", "Sequence")
                        .IsUnique();

                    b.ToTable("MealRegistrations");
                });

            modelBuilder.Entity("MealTrace.Api.Data.MenuDish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MealDayId");

                    b.HasIndex("RecipeVersionId");

                    b.ToTable("MenuDishes");
                });

            modelBuilder.Entity("MealTrace.Api.Data.ParentStudent", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ParentStudents");
                });

            modelBuilder.Entity("MealTrace.Api.Data.PortionSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CutoffAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MealDayId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettledBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("MealDayId", "ClassId")
                        .IsUnique()
                        .HasFilter("\"ClassId\" IS NOT NULL");

                    b.HasIndex("MealDayId", "SettledAt");

                    b.ToTable("PortionSettlements");
                });

            modelBuilder.Entity("MealTrace.Api.Data.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MealTrace.Api.Data.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("GramsPerPortion")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("IngredientVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngredientVersionId");

                    b.HasIndex("RecipeVersionId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("MealTrace.Api.Data.RecipeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Version")
                        .IsUnique();

                    b.ToTable("RecipeVersions");
                });

            modelBuilder.Entity("MealTrace.Api.Data.ReportSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostPerPortion")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EnergyKcalPerPortion")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("MealDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("MealDayId");

                    b.HasIndex("SettlementId");

                    b.ToTable("ReportSnapshots");
                });

            modelBuilder.Entity("MealTrace.Api.Data.SchoolClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYear", "Name")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("MealTrace.Api.Data.SettlementStudent", b =>
                {
                    b.Property<Guid>("PortionSettlementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PortionSettlementId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("SettlementStudents");
                });

            modelBuilder.Entity("MealTrace.Api.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MealTrace.Api.Data.TeacherAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("TeacherAssignments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MealTrace.Api.Data.AccountPasswordResetAudit", b =>
                {
                    b.HasOne("MealTrace.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MealTrace.Api.Data.Enrollment", b =>
                {
                    b.HasOne("MealTrace.Api.Data.SchoolClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("EndedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealTrace.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealTrace.Api.Data.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MealTrace.Api.Data.IngredientVersion", b =>
                {
                    b.HasOne("MealTrace.Api.Data.Ingredient", "Ingredient")
                        .WithMany("Versions")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MealTrace.Api.Data.InspectorGrant", b =>
                {
                    b.HasOne("MealTrace.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("GrantedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.ApplicationUser", "User")
                        .WithOne("InspectorGrant")
                        .HasForeignKey("MealTrace.Api.Data.InspectorGrant", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealTrace.Api.Data.MealAbsence", b =>
                {
                    b.HasOne("MealTrace.Api.Data.ApplicationUser", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedBy");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MealTrace.Api.Data.MealEvidence", b =>
                {
                    b.HasOne("MealTrace.Api.Data.MealDay", "MealDay")
                        .WithMany("Evidence")
                        .HasForeignKey("MealDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealDay");
                });

            modelBuilder.Entity("MealTrace.Api.Data.MealRegistration", b =>
                {
                    b.HasOne("MealTrace.Api.Data.MealDay", "MealDay")
                        .WithMany("Registrations")
                        .HasForeignKey("MealDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealTrace.Api.Data.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealDay");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MealTrace.Api.Data.MenuDish", b =>
                {
                    b.HasOne("MealTrace.Api.Data.MealDay", "MealDay")
                        .WithMany("Dishes")
                        .HasForeignKey("MealDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.RecipeVersion", "RecipeVersion")
                        .WithMany()
                        .HasForeignKey("RecipeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealDay");

                    b.Navigation("RecipeVersion");
                });

            modelBuilder.Entity("MealTrace.Api.Data.ParentStudent", b =>
                {
                    b.HasOne("MealTrace.Api.Data.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.ApplicationUser", "User")
                        .WithMany("ParentStudents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealTrace.Api.Data.PortionSettlement", b =>
                {
                    b.HasOne("MealTrace.Api.Data.SchoolClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("MealTrace.Api.Data.MealDay", "MealDay")
                        .WithMany("Settlements")
                        .HasForeignKey("MealDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("MealDay");
                });

            modelBuilder.Entity("MealTrace.Api.Data.RecipeIngredient", b =>
                {
                    b.HasOne("MealTrace.Api.Data.IngredientVersion", "IngredientVersion")
                        .WithMany()
                        .HasForeignKey("IngredientVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.RecipeVersion", "RecipeVersion")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientVersion");

                    b.Navigation("RecipeVersion");
                });

            modelBuilder.Entity("MealTrace.Api.Data.RecipeVersion", b =>
                {
                    b.HasOne("MealTrace.Api.Data.Recipe", "Recipe")
                        .WithMany("Versions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealTrace.Api.Data.ReportSnapshot", b =>
                {
                    b.HasOne("MealTrace.Api.Data.MealDay", "MealDay")
                        .WithMany()
                        .HasForeignKey("MealDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.PortionSettlement", "Settlement")
                        .WithMany()
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealDay");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("MealTrace.Api.Data.SettlementStudent", b =>
                {
                    b.HasOne("MealTrace.Api.Data.PortionSettlement", "PortionSettlement")
                        .WithMany("Students")
                        .HasForeignKey("PortionSettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PortionSettlement");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MealTrace.Api.Data.Student", b =>
                {
                    b.HasOne("MealTrace.Api.Data.SchoolClass", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("MealTrace.Api.Data.TeacherAssignment", b =>
                {
                    b.HasOne("MealTrace.Api.Data.SchoolClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.ApplicationUser", "User")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MealTrace.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MealTrace.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealTrace.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MealTrace.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealTrace.Api.Data.ApplicationUser", b =>
                {
                    b.Navigation("InspectorGrant");

                    b.Navigation("ParentStudents");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("MealTrace.Api.Data.Ingredient", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MealTrace.Api.Data.MealDay", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Evidence");

                    b.Navigation("Registrations");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("MealTrace.Api.Data.PortionSettlement", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("MealTrace.Api.Data.Recipe", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MealTrace.Api.Data.RecipeVersion", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MealTrace.Api.Data.SchoolClass", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("MealTrace.Api.Data.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
