import { useQuery } from '@tanstack/react-query'
import { api } from '../../lib/api'
import { Database, UtensilsCrossed } from 'lucide-react'
import { useState } from 'react'

type MealDay = { id: string; date: string; mealType: string; publishedAt: string | null; settledPortions: number | null; dishes: { id: string; name: string; recipeVersionId: string }[] }
type Detail = Omit<MealDay, 'settledPortions'> & { cutoffAt: string; settlements: { id: string; classId: string | null; className: string | null; count: number; settledAt: string }[]; evidence: { id: string; kind: string; description: string; capturedAt: string; syncedAt: string; photoUrl: string | null }[] }
const date = (value: string) => new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium' }).format(new Date(`${value}T00:00:00`))

export function MealDaysPage() {
  const [selected, setSelected] = useState<string | null>(null)
  const days = useQuery({ queryKey: ['meal-days'], queryFn: async () => (await api.get<MealDay[]>('/meal-days')).data })
  const detail = useQuery({ queryKey: ['meal-day', selected], queryFn: async () => (await api.get<Detail>(`/meal-days/${selected}`)).data, enabled: !!selected })
  const items = days.data ?? []

  if (selected) return <><button type="button" className="back" onClick={() => setSelected(null)}>← Quay lại tổng quan</button><div className="eyebrow">HỒ SƠ THỰC HIỆN BỮA ĂN</div>{detail.isPending ? <p>Đang tải…</p> : detail.isError ? <p className="error">Không tải được hồ sơ.</p> : detail.data && <><h1>{detail.data.mealType} · {date(detail.data.date)}</h1><p className="lead">Đối chiếu thực đơn, số suất chốt và minh chứng.</p><div className="grid"><section className="panel"><h2>Thực đơn dự kiến</h2>{detail.data.dishes.length ? detail.data.dishes.map(d => <div className="entry" key={d.id}>{d.name}<small>Recipe version: {d.recipeVersionId}</small></div>) : <p className="empty">Chưa có món ăn.</p>}</section><section className="panel"><h2>Số suất chốt</h2><strong className="big">{detail.data.settlements.length ? detail.data.settlements.some(s => s.classId) ? detail.data.settlements.filter(s => s.classId).reduce((sum, s) => sum + s.count, 0) : detail.data.settlements.at(-1)?.count : '—'}</strong><p className="note">Cut-off: {new Date(detail.data.cutoffAt).toLocaleString('vi-VN')}</p><p className="note">{detail.data.settlements.length} bản ghi theo lớp</p></section></div><section className="panel evidence"><h2>Minh chứng bữa ăn</h2>{detail.data.evidence.length ? detail.data.evidence.map(e => <div className="entry" key={e.id}><strong>{e.kind}</strong> — {e.description}<small>Chụp: {new Date(e.capturedAt).toLocaleString('vi-VN')} · Đồng bộ: {new Date(e.syncedAt).toLocaleString('vi-VN')}</small>{e.photoUrl && <a href={e.photoUrl} target="_blank" rel="noreferrer">Xem ảnh</a>}</div>) : <p className="empty">Chưa có minh chứng.</p>}</section></>}</>

  return <><div className="eyebrow">HỆ THỐNG QUẢN LÝ BỮA ĂN BÁN TRÚ</div><h1>Tổng quan ngày ăn</h1><p className="lead">Theo dõi thực đơn, số suất đã chốt và hồ sơ thực hiện bữa ăn.</p><div className="stats"><div><span>Ngày ăn trong danh sách</span><strong>{days.isPending ? '—' : items.length}</strong></div><div><span>Thực đơn công bố</span><strong>{days.isPending ? '—' : items.filter(x => x.publishedAt).length}</strong></div><div><span>Ngày đã chốt suất</span><strong>{days.isPending ? '—' : items.filter(x => x.settledPortions !== null).length}</strong></div></div><section className="panel"><div className="panel-head"><div><h2>Danh sách ngày ăn</h2><p>Dữ liệu trực tiếp từ MealTrace API; tối đa 100 bản ghi.</p></div><UtensilsCrossed size={22} /></div>{days.isPending ? <p className="empty">Đang tải dữ liệu…</p> : days.isError ? <p className="empty error">Chưa kết nối được API. Hãy chạy backend và PostgreSQL.</p> : !items.length ? <div className="empty"><Database size={30} /><h3>Chưa có ngày ăn</h3><p>Database đã sẵn sàng cho thực đơn đầu tiên.</p></div> : items.map(day => <button type="button" className="row" key={day.id} onClick={() => setSelected(day.id)}><span className="date">{day.date.slice(8, 10)}<small>THÁNG {day.date.slice(5, 7)}</small></span><span className="row-text"><strong>{day.mealType} · {date(day.date)}</strong><small>{day.dishes.map(d => d.name).join(' · ') || 'Chưa gắn món ăn'}</small></span><span className="badge">{day.settledPortions === null ? 'Chưa chốt suất' : `${day.settledPortions} suất`}</span>›</button>)}</section></>
}
